/** ステージ一覧。森はID6から順に追加し、layouts.tsに地形を登録できます。 */
import type { Stage } from '../game/types';
import { DEFAULT_TRAP_POOL } from '../data/traps';
// Radius 5 reveals the added, half-clipped outer ring of the 11×11 view.
export const STAGES: Stage[] = [
  { id: 1, dungeon: { floors: 1, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '平原1', subtitle: 'はじまりの平原', description: '小さな冒険のはじまり。まずは一歩を踏み出そう。', objective: '古代の宝箱を1個回収し、出口へ', vision: 5, width: 19, height: 19, enemyCount: 5, enemySpawns: [{ kind: 'slime', count: 5 }], trapPlacements: [{ count: 6, pool: DEFAULT_TRAP_POOL }], goal: 'treasure', requiredChests: 1 },
  { id: 2, dungeon: { floors: 1, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '平原2', subtitle: '荒れ果てた平原', description: '放置された平原の調査へ', objective: '戦闘を回避しながら、出口へ', vision: 5, width: 23, height: 21, enemyCount: 9, enemySpawns: [{ kind: 'slime', count: 1 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 1 }], trapPlacements: [{ count: 7, pool: DEFAULT_TRAP_POOL }], goal: 'exit', requiredChests: 0 },
  { id: 3, dungeon: { floors: 2, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '平原3', subtitle: 'うす暗い獣道', description: '草陰に潜む狼。視線をかわし、森の向こうへ。', objective: '戦闘を回避しながら、出口へ', vision: 5, width: 25, height: 23, enemyCount: 11, enemySpawns: [{ kind: 'slime', count: 1 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }], trapPlacements: [{ count: 8, pool: DEFAULT_TRAP_POOL }], goal: 'treasure', requiredChests: 2 },
  { id: 4, dungeon: { floors: 2, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '平原4', subtitle: 'おおかみの縄張り', description: 'おおかみの群れを掃討せよ', objective: 'おおかみの群れを倒そう', vision: 5, width: 25, height: 25, enemyCount: 11, enemySpawns: [{ kind: 'golem', count: 1, position: { x: 18, y: 18 } }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }], trapPlacements: [{ count: 9, pool: DEFAULT_TRAP_POOL }], goal: 'hunt', requiredChests: 0 },
  { id: 5, dungeon: { floors: 2, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '平原5', subtitle: '廃棄された村', description: '住み着いたゴブリンを駆逐せよ', objective: 'エリートゴブリンを倒そう', vision: 5, width: 27, height: 25, enemyCount: 10, enemySpawns: [{ kind: 'boss', count: 1, position: { x: 20, y: 18 } }, { kind: 'goblin', count: 4 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }], trapPlacements: [{ count: 10, pool: DEFAULT_TRAP_POOL }], goal: 'boss', requiredChests: 0 },
  { id: 6, dungeon: { floors: 3, enemyScaling: { everyFloors: 3, multiplier: 1.2 }, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '森1',   subtitle: '迷いの森', description: '魔物を退けながら出口を目指せ', objective: '森の出口を探そう', vision: 5, width: 35, height: 54, enemyCount: 12, enemySpawns: [{ kind: 'golem', count: 2 }, { kind: 'wolf', count: 7 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }], trapPlacements: [{ count: 9, pool: DEFAULT_TRAP_POOL }], goal: 'exit', requiredChests: 0, sleepRespawnCount: 3 },
  { id: 7, dungeon: { floors: 3, enemyScaling: { everyFloors: 3, multiplier: 1.2 }, gemCount: 1, extraPassages: 16, enemyVariance: 1, nightRevival: { min: 1, max: 2 } }, name: '森2',   subtitle: '迷いの森 中層', description: '魔物を退けながら出口を目指せ', objective: '森の出口を探そう', vision: 5, width: 39, height: 60, enemyCount: 15, enemySpawns: [{ kind: 'golem', count: 2 }, { kind: 'wolf', count: 7 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }, { kind: 'wolf', count: 1 }, { kind: 'slime', count: 2 }, { kind: 'wolf', count: 1 }], trapPlacements: [{ count: 9, pool: DEFAULT_TRAP_POOL }], goal: 'exit', requiredChests: 0, sleepRespawnCount: 3 },
  { id: 8, name: '森3', subtitle: 'ゴブリンの迷い森', description: '曲がりくねる獣道と輪を描く森。ゴブリンの集落を抜けよう。', objective: '森の出口を探そう', vision: 5, width: 41, height: 65, enemyCount: 22, goal: 'exit', requiredChests: 0, sleepRespawnCount: 3, dungeon: { floors: 3, enemyScaling: { everyFloors: 3, multiplier: 1.2 }, gemCount: 1, extraPassages: 8, enemyVariance: 1, nightRevival: { min: 1, max: 2 } } },
];
